# Mapping ancient CF unicode math to LaTeX
UNICODE_TO_LATEX = {
  # Relational & Math Operators
  "≤": r"\le",
  "≥": r"\ge",
  "≠": r"\ne",
  "×": r"\times",
  "·": r"\cdot",
  "⋅": r"\cdot",  # U+22C5 DOT OPERATOR (newer statements)
  "…": r"\dots",
  "±": r"\pm",
  "≈": r"\approx",
  "≡": r"\equiv",
  "−": "-",  # U+2212 Minus Sign -> standard minus
  "∗": "*",  # U+2217 ASTERISK OPERATOR (footnote mark)
  "†": r"\dagger",  # U+2020 DAGGER (footnote mark)
  "²": "^2",
  "³": "^3",
  "½": r"\frac{1}{2}",
  "¼": r"\frac{1}{4}",
  "¾": r"\frac{3}{4}",
  "√": r"\sqrt",
  "∝": r"\propto",
  "∠": r"\angle",
  "°": r"^\circ",
  "△": r"\triangle",
  # Sets & Logic
  "∅": r"\emptyset",
  "∪": r"\cup",
  "∩": r"\cap",
  "⊂": r"\subset",
  "⊆": r"\subseteq",
  "∈": r"\in",
  "∉": r"\notin",
  "∀": r"\forall",
  "∃": r"\exists",
  "∇": r"\nabla",
  "⊕": r"\oplus",
  "⊗": r"\otimes",
  "⌊": r"\lfloor",
  "⌋": r"\rfloor",
  "⌈": r"\lceil",
  "⌉": r"\rceil",
  # Arrows
  "→": r"\rightarrow",
  "←": r"\leftarrow",
  "↔": r"\leftrightarrow",
  "⇒": r"\Rightarrow",
  "⇔": r"\Leftrightarrow",
  "↑": r"\uparrow",
  "↓": r"\downarrow",
  # Greek Alphabet (Lower & Upper)
  "α": r"\alpha",
  "β": r"\beta",
  "γ": r"\gamma",
  "δ": r"\delta",
  "ε": r"\varepsilon",
  "ζ": r"\zeta",
  "η": r"\eta",
  "θ": r"\theta",
  "ι": r"\iota",
  "κ": r"\kappa",
  "λ": r"\lambda",
  "μ": r"\mu",
  "ν": r"\nu",
  "ξ": r"\xi",
  "π": r"\pi",
  "ρ": r"\rho",
  "σ": r"\sigma",
  "τ": r"\tau",
  "υ": r"\upsilon",
  "φ": r"\varphi",
  "χ": r"\chi",
  "ψ": r"\psi",
  "ω": r"\omega",
  "Γ": r"\Gamma",
  "Δ": r"\Delta",
  "Θ": r"\Theta",
  "Λ": r"\Lambda",
  "Ξ": r"\Xi",
  "Π": r"\Pi",
  "Σ": r"\Sigma",
  "Φ": r"\Phi",
  "Ψ": r"\Psi",
  "Ω": r"\Omega",
  "∞": r"\infty",
}
